// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShippingApp.Data;

#nullable disable

namespace ShippingApp.Migrations
{
    [DbContext(typeof(ShippingDbContext))]
    [Migration("20230509065941_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShippingApp.Models.TransactionRecords", b =>
                {
                    b.Property<Guid>("transactionRecordsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("isPaid")
                        .HasColumnType("bit");

                    b.Property<string>("orderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("transactionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("transactionRecordsId");

                    b.ToTable("TransactionRecords");
                });

            modelBuilder.Entity("ShippingApp.Models.User", b =>
                {
                    b.Property<Guid>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("contactNo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("otpUsableTill")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("passwordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("pathToProfilePic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("userRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("verificationOTP")
                        .HasColumnType("int");

                    b.Property<DateTime?>("verifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("userId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            userId = new Guid("59e4843d-f2a5-4570-acf7-f2d814e1738c"),
                            address = "address",
                            contactNo = 9865326598L,
                            createdAt = new DateTime(2023, 5, 9, 12, 29, 41, 803, DateTimeKind.Local).AddTicks(3205),
                            email = "admin@gmail.com",
                            firstName = "Admin",
                            isDeleted = false,
                            lastName = "Admin",
                            otpUsableTill = new DateTime(2023, 5, 9, 12, 29, 41, 803, DateTimeKind.Local).AddTicks(3216),
                            passwordHash = new byte[] { 8, 151, 35, 64, 98, 188, 240, 221, 74, 208, 219, 16, 70, 134, 10, 16, 57, 83, 242, 218, 134, 209, 18, 168, 96, 254, 75, 50, 249, 152, 36, 152, 154, 235, 192, 53, 118, 215, 167, 35, 151, 189, 180, 117, 133, 22, 166, 2, 234, 12, 105, 26, 205, 50, 126, 134, 244, 220, 11, 18, 168, 167, 141, 144 },
                            pathToProfilePic = "pathToProfilePic",
                            token = "",
                            updatedAt = new DateTime(2023, 5, 9, 12, 29, 41, 803, DateTimeKind.Local).AddTicks(3215),
                            userRole = "admin",
                            verificationOTP = 999,
                            verifiedAt = new DateTime(2023, 5, 9, 12, 29, 41, 803, DateTimeKind.Local).AddTicks(3217)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
